# Target specific macros
TARGET = MotorRegTest
TARGET_SOURCES = 										\
	./src/MotorRegulatorTest.c 							\
	./src/MotorRegulator.c
TOPPERS_OSEK_OIL_SOURCE = MotorRegulatorTest.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
