# Target specific macros
TARGET = JointTest
TARGET_SOURCES = 							\
	./src/JointTest.c						\
	./src/JointController.c					\
	./src/MotorRegulator.c
TOPPERS_OSEK_OIL_SOURCE = JointTest.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
