classdef ReferenceOscillator < instrument.ivic.IviGroupBase
    %REFERENCEOSCILLATOR This class contains functions to
    %perform the calibration.
    
    % Copyright 2010 The MathWorks, Inc.
    
    %% Public Methods
    methods
        function ConfigureRefOscillatorEnabled(obj,ReferenceOscillatorEnabled)
            %CONFIGUREREFOSCILLATORENABLED This function enables or
            %disables the reference oscillator.
            
            narginchk(2,2)
            ReferenceOscillatorEnabled = obj.checkScalarBoolArg(ReferenceOscillatorEnabled);
            try
                [libname, session ] = obj.getLibraryAndSession();
                
                status = calllib( libname,'IviPwrMeter_ConfigureRefOscillatorEnabled', session, ReferenceOscillatorEnabled);
                
                obj.checkError(status);
            catch e
                throwAsCaller(e);
            end
        end
        
        function ConfigureRefOscillator(obj,Frequency,Level)
            %CONFIGUREREFOSCILLATOR This function sets the frequency
            %and power level of the signal generated by the reference
            %oscillator.
            
            narginchk(3,3)
            Frequency = obj.checkScalarDoubleArg(Frequency);
            Level = obj.checkScalarDoubleArg(Level);
            try
                [libname, session ] = obj.getLibraryAndSession();
                
                status = calllib( libname,'IviPwrMeter_ConfigureRefOscillator', session, Frequency, Level);
                
                obj.checkError(status);
            catch e
                throwAsCaller(e);
            end
        end
    end
end
