# Target specific macros
TARGET = TouchMUX_Test
TARGET_SOURCES = src/TouchMUX_Test.c
TOPPERS_OSEK_OIL_SOURCE = ./TouchMUX_Test.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
